# Generated by Django 6.1.1 on 2026-09-21 08:00

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Homepage'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='One or more paragraphs introducing you. Rendered under the hero heading.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_body',
            field=models.TextField(blank=True, default='Open to conversations about engineering roles, collaboration, or anything backend-and-Africa shaped.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_heading',
            field=models.CharField(default="Let's build something.", max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_heading',
            field=models.CharField(default='I build systems that work — then I make sure they work for the people who actually use them.', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='terminal_prompt',
            field=models.CharField(default='holland@dev:~$ whoami', help_text='Small mono eyebrow line above the headline.', max_length=60),
        ),
        migrations.CreateModel(
            name='HomePageSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=50)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
