# Generated by Django 6.1.1 on 2026-09-21 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_homepage_options_homepage_about_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='terminal_prompt',
            new_name='home_subtitle',
        ),
    ]
