# Generated by Django 5.2.13 on 2026-04-20 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepageaside'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepageaside',
            options={'verbose_name_plural': 'Home Page Aside'},
        ),
    ]
