# Generated by Django 5.2.13 on 2026-04-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homepagesociallinks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagesociallinks',
            name='anchor',
        ),
        migrations.AddField(
            model_name='homepagesociallinks',
            name='url',
            field=models.URLField(blank=True, help_text='Link to social profile', max_length=255, null=True),
        ),
    ]
