# Generated by Django 5.2.13 on 2026-04-23 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_homepagesociallinks_anchor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_cta',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_cta_link',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='image',
        ),
    ]
