# Generated by Django 5.2.13 on 2026-04-24 00:00

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_homepage_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about',
            field=wagtail.fields.RichTextField(default="I'm a junior software engineer who enjoys building web applications with Python, Django, React, Next.js and TypeScript. I'm especially interested in backend systems, clean architecture, and understanding how the pieces of a system fit together. Most of my time is spent building projects, learning new things, and getting better at the craft of software engineering."),
            preserve_default=False,
        ),
    ]
