# Generated by Django 5.2.13 on 2026-04-24 06:52

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_homepage_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='experience',
            field=wagtail.fields.StreamField([('heading', 0), ('period', 0), ('description', 1), ('tags', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Enter comma-separated tags', 'required': False})}, help_text='Use this section to list your experience'),
        ),
    ]
