# Generated by Django 5.2.13 on 2026-04-24 07:21

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_homepage_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='experience',
            field=wagtail.fields.StreamField([('experience', 3)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Enter comma-separated tags', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('period', 0), ('description', 1), ('tags', 2)]], {})}),
        ),
    ]
