# Generated by Django 5.2.13 on 2026-04-24 07:24

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_homepage_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='experience',
            field=wagtail.fields.StreamField([('experience', 4)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Enter comma-separated tags', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('company', 0), ('role', 0), ('period', 1), ('description', 2), ('tags', 3)]], {})}),
        ),
    ]
