# Generated by Django 5.2.13 on 2026-04-14 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NavigatiionSettings',
            new_name='NavigationSettings',
        ),
    ]
